import React from 'react';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import '@/styles/globals.scss'
import { StoreProvider } from '@/store/StoreProvider';

export const metadata = {
  title: 'I-Cleaning',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body >
      <StoreProvider>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </StoreProvider>
      <script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>
    </body>
  </html>
);

export default RootLayout;
