import React from 'react';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import '@/styles/globals.scss'
import { StoreProvider } from '@/store/StoreProvider';
import Head from 'next/head';

export const metadata = {
  title: 'I-Cleaning',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html lang="en">
    <Head>
      <link rel="icon" href="/public/favicon.ico" sizes='any' />
    </Head>
    <body>
      <StoreProvider>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </StoreProvider>
    </body>
  </html>
);

export default RootLayout;
